-- CONSULTAS SQL
-- CONSULTAS DE AUDITORIA
-- findAll AUDITORIA
SELECT AUDITORIA.AUD_ID,
  AUDITORIA.AUD_TABELA,
  AUDITORIA.AUD_EVENTO,
  AUDITORIA.AUD_DATA,
  AUDITORIA.AUD_USU_SO,
  AUDITORIA.AUD_USU_BD,
  AUDITORIA.AUD_IDENT_HOST,
  AUDITORIA.AUD_IDENT_TERMINAL
FROM PABLO.AUDITORIA;
-- findById AUDITORIA
SELECT AUDITORIA.AUD_ID,
  AUDITORIA.AUD_TABELA,
  AUDITORIA.AUD_EVENTO,
  AUDITORIA.AUD_DATA,
  AUDITORIA.AUD_USU_SO,
  AUDITORIA.AUD_USU_BD,
  AUDITORIA.AUD_IDENT_HOST,
  AUDITORIA.AUD_IDENT_TERMINAL
FROM PABLO.AUDITORIA
WHERE AUDITORIA.AUD_ID =
  &AUD_ID;
  -- findByDate AUDITORIA
SELECT AUDITORIA.AUD_ID,
  AUDITORIA.AUD_TABELA,
  AUDITORIA.AUD_EVENTO,
  AUDITORIA.AUD_DATA,
  AUDITORIA.AUD_USU_SO,
  AUDITORIA.AUD_USU_BD,
  AUDITORIA.AUD_IDENT_HOST,
  AUDITORIA.AUD_IDENT_TERMINAL
FROM PABLO.AUDITORIA
WHERE
  AUDITORIA.AUD_DATA LIKE
  '&DATA';
-- findByCampo AUDITORIA
SELECT AUDITORIA.AUD_ID,
  AUDITORIA.AUD_TABELA,
  AUDITORIA.AUD_EVENTO,
  AUDITORIA.AUD_DATA,
  AUDITORIA.AUD_USU_SO,
  AUDITORIA.AUD_USU_BD,
  AUDITORIA.AUD_IDENT_HOST,
  AUDITORIA.AUD_IDENT_TERMINAL
FROM PABLO.AUDITORIA
WHERE
  &CAMPO =
  &VALOR;
-- CONSULTAS DE CATEGORIA
-- findAll CATEGORIA
SELECT CATEGORIA.CAT_ID,
  CATEGORIA.CAT_DESCRICAO,
  CATEGORIA.CAT_QTD_UPDATE,
  CATEGORIA.CAT_DATA_CONTROLE
FROM PABLO.CATEGORIA;
-- findById CATEGORIA
SELECT CATEGORIA.CAT_ID,
  CATEGORIA.CAT_DESCRICAO,
  CATEGORIA.CAT_QTD_UPDATE,
  CATEGORIA.CAT_DATA_CONTROLE
FROM PABLO.CATEGORIA
WHERE CATEGORIA.CAT_ID =
  &CAT_ID;
-- findByNome CATEGORIA
SELECT CATEGORIA.CAT_ID,
  CATEGORIA.CAT_DESCRICAO,
  CATEGORIA.CAT_QTD_UPDATE,
  CATEGORIA.CAT_DATA_CONTROLE
FROM PABLO.CATEGORIA
WHERE CATEGORIA.CAT_DESCRICAO = '&DESCRICAO_DA_CATEGORIA';
-- findByCampo CATEGORIA
SELECT CATEGORIA.CAT_ID,
  CATEGORIA.CAT_DESCRICAO,
  CATEGORIA.CAT_QTD_UPDATE,
  CATEGORIA.CAT_DATA_CONTROLE
FROM PABLO.CATEGORIA
WHERE
  &CAMPO =
  &VALOR;
-- CONSULTAS DE COMPRA
-- findAll COMPRA
SELECT COMPRA.CMP_ID,
  COMPRA.CMP_DATA,
  COMPRA.CMP_VALOR_TOTAL,
  COMPRA.CMP_PDV_ID,
  COMPRA.CMP_QTD_UPDATE,
  COMPRA.CMP_DATA_CONTROLE
FROM PABLO.COMPRA;
-- findById COMPRA
SELECT COMPRA.CMP_ID,
  COMPRA.CMP_DATA,
  COMPRA.CMP_VALOR_TOTAL,
  COMPRA.CMP_PDV_ID,
  COMPRA.CMP_QTD_UPDATE,
  COMPRA.CMP_DATA_CONTROLE
FROM PABLO.COMPRA
WHERE COMPRA.CMP_ID =
  &CMP_ID;
  -- findByDate COMPRA
SELECT COMPRA.CMP_ID,
  COMPRA.CMP_DATA,
  COMPRA.CMP_VALOR_TOTAL,
  COMPRA.CMP_PDV_ID,
  COMPRA.CMP_QTD_UPDATE,
  COMPRA.CMP_DATA_CONTROLE
FROM PABLO.COMPRA
WHERE
  COMPRA.CMP_DATA LIKE
  '&DATA';
-- findByCampo COMPRA
SELECT COMPRA.CMP_ID,
  COMPRA.CMP_DATA,
  COMPRA.CMP_VALOR_TOTAL,
  COMPRA.CMP_PDV_ID,
  COMPRA.CMP_QTD_UPDATE,
  COMPRA.CMP_DATA_CONTROLE
FROM PABLO.COMPRA
WHERE
  &CAMPO =
  &VALOR;
-- CONSULTAS DE ENDERECO_FORNECEDOR
-- findAll ENDERECO_FORNECEDOR
SELECT ENDERECO_FORNECEDOR.END_ID,
  ENDERECO_FORNECEDOR.END_FOR_ID,
  ENDERECO_FORNECEDOR.END_LOGRADOURO,
  ENDERECO_FORNECEDOR.END_CEP,
  ENDERECO_FORNECEDOR.END_BAIRRO,
  ENDERECO_FORNECEDOR.END_CIDADE,
  ENDERECO_FORNECEDOR.END_ESTADO,
  ENDERECO_FORNECEDOR.END_QTD_UPDATE,
  ENDERECO_FORNECEDOR.END_DATA_CONTROLE
FROM PABLO.ENDERECO_FORNECEDOR;
-- findById ENDERECO_FORNECEDOR
SELECT ENDERECO_FORNECEDOR.END_ID,
  ENDERECO_FORNECEDOR.END_FOR_ID,
  ENDERECO_FORNECEDOR.END_LOGRADOURO,
  ENDERECO_FORNECEDOR.END_CEP,
  ENDERECO_FORNECEDOR.END_BAIRRO,
  ENDERECO_FORNECEDOR.END_CIDADE,
  ENDERECO_FORNECEDOR.END_ESTADO,
  ENDERECO_FORNECEDOR.END_QTD_UPDATE,
  ENDERECO_FORNECEDOR.END_DATA_CONTROLE
FROM PABLO.ENDERECO_FORNECEDOR
WHERE ENDERECO_FORNECEDOR.END_ID =
  &END_ID;
-- findByCampo ENDERECO_FORNECEDOR
SELECT ENDERECO_FORNECEDOR.END_ID,
  ENDERECO_FORNECEDOR.END_FOR_ID,
  ENDERECO_FORNECEDOR.END_LOGRADOURO,
  ENDERECO_FORNECEDOR.END_CEP,
  ENDERECO_FORNECEDOR.END_BAIRRO,
  ENDERECO_FORNECEDOR.END_CIDADE,
  ENDERECO_FORNECEDOR.END_ESTADO,
  ENDERECO_FORNECEDOR.END_QTD_UPDATE,
  ENDERECO_FORNECEDOR.END_DATA_CONTROLE
FROM PABLO.ENDERECO_FORNECEDOR
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE FORNECEDOR
-- findAll FORNECEDOR
SELECT FORNECEDOR.FOR_ID,
  FORNECEDOR.FOR_RESPONSAVEL_NOME,
  FORNECEDOR.FOR_RESPONSAVEL_NOMEDOMEIO,
  FORNECEDOR.FOR_RESPONSAVEL_SOBRENOME,
  FORNECEDOR.FOR_CNPJ,
  FORNECEDOR.FOR_RAZAO_SOCIAL,
  FORNECEDOR.FOR_TELEFONE,
  FORNECEDOR.FOR_EMAIL,
  FORNECEDOR.FOR_QTD_UPDATE,
  FORNECEDOR.FOR_DATA_CONTROLE
FROM PABLO.FORNECEDOR;
-- findById FORNECEDOR
SELECT FORNECEDOR.FOR_ID,
  FORNECEDOR.FOR_RESPONSAVEL_NOME,
  FORNECEDOR.FOR_RESPONSAVEL_NOMEDOMEIO,
  FORNECEDOR.FOR_RESPONSAVEL_SOBRENOME,
  FORNECEDOR.FOR_CNPJ,
  FORNECEDOR.FOR_RAZAO_SOCIAL,
  FORNECEDOR.FOR_TELEFONE,
  FORNECEDOR.FOR_EMAIL,
  FORNECEDOR.FOR_QTD_UPDATE,
  FORNECEDOR.FOR_DATA_CONTROLE
FROM PABLO.FORNECEDOR
WHERE FORNECEDOR.FOR_ID =
  &FOR_ID;
-- findByName FORNECEDOR
SELECT FORNECEDOR.FOR_ID,
  FORNECEDOR.FOR_RESPONSAVEL_NOME, 
  FORNECEDOR.FOR_RESPONSAVEL_NOMEDOMEIO, 
  FORNECEDOR.FOR_RESPONSAVEL_SOBRENOME,
  FORNECEDOR.FOR_CNPJ,
  FORNECEDOR.FOR_RAZAO_SOCIAL,
  FORNECEDOR.FOR_TELEFONE,
  FORNECEDOR.FOR_EMAIL,
  FORNECEDOR.FOR_QTD_UPDATE,
  FORNECEDOR.FOR_DATA_CONTROLE
FROM PABLO.FORNECEDOR
WHERE FORNECEDOR.FOR_RESPONSAVEL_NOME LIKE UPPER ('&NOME') AND
  (FORNECEDOR.FOR_RESPONSAVEL_NOMEDOMEIO LIKE UPPER('&NOME_DO_MEIO') AND
  FORNECEDOR.FOR_RESPONSAVEL_SOBRENOME LIKE UPPER('&SOBRENOMENOME'));
-- findByCampo FORNECEDOR
SELECT FORNECEDOR.FOR_ID,
  FORNECEDOR.FOR_RESPONSAVEL_NOME,
  FORNECEDOR.FOR_RESPONSAVEL_NOMEDOMEIO,
  FORNECEDOR.FOR_RESPONSAVEL_SOBRENOME,
  FORNECEDOR.FOR_CNPJ,
  FORNECEDOR.FOR_RAZAO_SOCIAL,
  FORNECEDOR.FOR_TELEFONE,
  FORNECEDOR.FOR_EMAIL,
  FORNECEDOR.FOR_QTD_UPDATE,
  FORNECEDOR.FOR_DATA_CONTROLE
FROM PABLO.FORNECEDOR
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE FUNCIONÁRIO
-- findAll FUNCIONÁRIO
SELECT FUNCIONARIO.FNC_ID,
  FUNCIONARIO.FNC_RG,
  FUNCIONARIO.FNC_CPF,
  FUNCIONARIO.FNC_NOME,
  FUNCIONARIO.FNC_NOMEDOMEIO,
  FUNCIONARIO.FNC_SOBRENOME,
  FUNCIONARIO.FNC_DATA_NASCIMENTO,
  FUNCIONARIO.FNC_CEP,
  FUNCIONARIO.FNC_BAIRRO,
  FUNCIONARIO.FNC_ESTADO,
  FUNCIONARIO.FNC_LOGRADOURO,
  FUNCIONARIO.FNC_CIDADE,
  FUNCIONARIO.FNC_TELEFONE,
  FUNCIONARIO.FNC_QTD_UPDATE,
  FUNCIONARIO.FNC_DATA_CONTROLE
FROM PABLO.FUNCIONARIO;
-- findById FUNCIONÁRIO
SELECT FUNCIONARIO.FNC_ID,
  FUNCIONARIO.FNC_RG,
  FUNCIONARIO.FNC_CPF,
  FUNCIONARIO.FNC_NOME,
  FUNCIONARIO.FNC_NOMEDOMEIO,
  FUNCIONARIO.FNC_SOBRENOME,
  FUNCIONARIO.FNC_DATA_NASCIMENTO,
  FUNCIONARIO.FNC_CEP,
  FUNCIONARIO.FNC_BAIRRO,
  FUNCIONARIO.FNC_ESTADO,
  FUNCIONARIO.FNC_LOGRADOURO,
  FUNCIONARIO.FNC_CIDADE,
  FUNCIONARIO.FNC_TELEFONE,
  FUNCIONARIO.FNC_QTD_UPDATE,
  FUNCIONARIO.FNC_DATA_CONTROLE
FROM PABLO.FUNCIONARIO
WHERE FUNCIONARIO.FNC_ID =
  &FNC_ID;
-- findByName FUNCIONÁRIO
SELECT FUNCIONARIO.FNC_ID,
  FUNCIONARIO.FNC_RG,
  FUNCIONARIO.FNC_CPF,
  FUNCIONARIO.FNC_NOME,
  FUNCIONARIO.FNC_NOMEDOMEIO,
  FUNCIONARIO.FNC_SOBRENOME,
  FUNCIONARIO.FNC_DATA_NASCIMENTO,
  FUNCIONARIO.FNC_CEP,
  FUNCIONARIO.FNC_BAIRRO,
  FUNCIONARIO.FNC_ESTADO,
  FUNCIONARIO.FNC_LOGRADOURO,
  FUNCIONARIO.FNC_CIDADE,
  FUNCIONARIO.FNC_TELEFONE,
  FUNCIONARIO.FNC_QTD_UPDATE,
  FUNCIONARIO.FNC_DATA_CONTROLE
FROM PABLO.FUNCIONARIO
WHERE FUNCIONARIO.FNC_NOME LIKE UPPER ('&NOME') AND
  (FUNCIONARIO.FNC_NOMEDOMEIO LIKE UPPER('&NOME_DO_MEIO') AND
  FUNCIONARIO.FNC_SOBRENOME LIKE UPPER('&SOBRENOME'));
-- findByCampo FUNCIONARIO
SELECT FUNCIONARIO.FNC_ID,
  FUNCIONARIO.FNC_RG,
  FUNCIONARIO.FNC_CPF,
  FUNCIONARIO.FNC_NOME,
  FUNCIONARIO.FNC_NOMEDOMEIO,
  FUNCIONARIO.FNC_SOBRENOME,
  FUNCIONARIO.FNC_DATA_NASCIMENTO,
  FUNCIONARIO.FNC_CEP,
  FUNCIONARIO.FNC_BAIRRO,
  FUNCIONARIO.FNC_ESTADO,
  FUNCIONARIO.FNC_LOGRADOURO,
  FUNCIONARIO.FNC_CIDADE,
  FUNCIONARIO.FNC_TELEFONE,
  FUNCIONARIO.FNC_QTD_UPDATE,
  FUNCIONARIO.FNC_DATA_CONTROLE
FROM PABLO.FUNCIONARIO
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE H_COMPRA
-- findAll H_COMPRA
SELECT H_COMPRA.HCM_ID,
  H_COMPRA.HCM_CMP_ID,
  H_COMPRA.HCM_CMP_DATA,
  H_COMPRA.HCM_CMP_VALOR_TOTAL,
  H_COMPRA.HCM_CMP_PDV_ID,
  H_COMPRA.HCM_DT_HIST
FROM PABLO.H_COMPRA;
-- findById H_COMPRA
SELECT H_COMPRA.HCM_ID,
  H_COMPRA.HCM_CMP_ID,
  H_COMPRA.HCM_CMP_DATA,
  H_COMPRA.HCM_CMP_VALOR_TOTAL,
  H_COMPRA.HCM_CMP_PDV_ID,
  H_COMPRA.HCM_DT_HIST
FROM PABLO.H_COMPRA
WHERE H_COMPRA.HCM_ID =
  &HCM_ID;
-- findByDate H_COMPRA
SELECT H_COMPRA.HCM_ID,
  H_COMPRA.HCM_CMP_ID,
  H_COMPRA.HCM_CMP_DATA,
  H_COMPRA.HCM_CMP_VALOR_TOTAL,
  H_COMPRA.HCM_CMP_PDV_ID,
  H_COMPRA.HCM_DT_HIST
FROM PABLO.H_COMPRA
WHERE H_COMPRA.HCM_DT_HIST LIKE
  '&DATA_HISTORICO';
-- findByCampo H_COMPRA
SELECT H_COMPRA.HCM_ID,
  H_COMPRA.HCM_CMP_ID,
  H_COMPRA.HCM_CMP_DATA,
  H_COMPRA.HCM_CMP_VALOR_TOTAL,
  H_COMPRA.HCM_CMP_PDV_ID,
  H_COMPRA.HCM_DT_HIST
FROM PABLO.H_COMPRA
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE H_OPERA_PDV
-- findAll H_OPERA_PDV
SELECT H_OPERA_PDV.HOP_ID,
  H_OPERA_PDV.HOP_OPE_DATA_ENTRADA,
  H_OPERA_PDV.HOP_OPE_DATA_SAIDA,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_PDV_ID,
  H_OPERA_PDV.HOP_DT_HIST
FROM PABLO.H_OPERA_PDV;
-- findById H_OPERA_PDV
SELECT H_OPERA_PDV.HOP_ID,
  H_OPERA_PDV.HOP_OPE_DATA_ENTRADA,
  H_OPERA_PDV.HOP_OPE_DATA_SAIDA,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_PDV_ID,
  H_OPERA_PDV.HOP_DT_HIST
FROM PABLO.H_OPERA_PDV
WHERE H_OPERA_PDV.HOP_ID =
  &HOP_ID;
-- findById H_OPERA_PDV
SELECT H_OPERA_PDV.HOP_ID,
  H_OPERA_PDV.HOP_OPE_DATA_ENTRADA,
  H_OPERA_PDV.HOP_OPE_DATA_SAIDA,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_PDV_ID,
  H_OPERA_PDV.HOP_DT_HIST
FROM PABLO.H_OPERA_PDV
WHERE H_OPERA_PDV.HOP_DT_HIST =
  '&DATA_HISTORICO';
-- findByCampo H_OPERA_PDV
SELECT H_OPERA_PDV.HOP_ID,
  H_OPERA_PDV.HOP_OPE_DATA_ENTRADA,
  H_OPERA_PDV.HOP_OPE_DATA_SAIDA,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_FNC_ID,
  H_OPERA_PDV.HOP_OPE_PDV_ID,
  H_OPERA_PDV.HOP_DT_HIST
FROM PABLO.H_OPERA_PDV
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE ITENS_COMPRA
-- findAll ITENS_COMPRA
SELECT ITENS_COMPRA.ITC_QUANTIDADE,
  ITENS_COMPRA.ITC_PRO_ID,
  ITENS_COMPRA.ITC_CMP_ID,
  ITENS_COMPRA.ITC_QTD_UPDATE,
  ITENS_COMPRA.ITC_DATA_CONTROLE
FROM PABLO.ITENS_COMPRA;
-- findById ITENS_COMPRA
SELECT ITENS_COMPRA.ITC_QUANTIDADE,
  ITENS_COMPRA.ITC_PRO_ID,
  ITENS_COMPRA.ITC_CMP_ID,
  ITENS_COMPRA.ITC_QTD_UPDATE,
  ITENS_COMPRA.ITC_DATA_CONTROLE
FROM PABLO.ITENS_COMPRA
WHERE ITENS_COMPRA.ITC_PRO_ID =
  &PRO_ID
AND ITENS_COMPRA.ITC_CMP_ID =
  &CMP_ID;
-- findByCampo ITENS_COMPRA
SELECT ITENS_COMPRA.ITC_QUANTIDADE,
  ITENS_COMPRA.ITC_PRO_ID,
  ITENS_COMPRA.ITC_CMP_ID,
  ITENS_COMPRA.ITC_QTD_UPDATE,
  ITENS_COMPRA.ITC_DATA_CONTROLE
FROM PABLO.ITENS_COMPRA
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE ITENS_PROMOCAO
-- findAll ITENS_PROMOCAO
SELECT ITENS_COMPRA.ITC_QUANTIDADE,
  ITENS_COMPRA.ITC_PRO_ID,
  ITENS_COMPRA.ITC_CMP_ID,
  ITENS_COMPRA.ITC_QTD_UPDATE,
  ITENS_COMPRA.ITC_DATA_CONTROLE
FROM PABLO.ITENS_PROMOCAO;
-- findById ITENS_PROMOCAO
SELECT ITENS_PROMOCAO.ITP_QTD_DISPONIVEL,
  ITENS_PROMOCAO.ITP_DESCONTO,
  ITENS_PROMOCAO.ITP_PRO_ID,
  ITENS_PROMOCAO.ITP_PRM_ID,
  ITENS_PROMOCAO.ITP_QTD_UPDATE,
  ITENS_PROMOCAO.ITP_DATA_CONTROLE
FROM PABLO.ITENS_PROMOCAO
WHERE ITENS_PROMOCAO.ITP_PRO_ID =
  &PRO_ID
AND ITENS_PROMOCAO.ITP_PRM_ID =
  &PRM_ID;
-- findByCampo ITENS_PROMOCAO
SELECT ITENS_PROMOCAO.ITP_QTD_DISPONIVEL,
  ITENS_PROMOCAO.ITP_DESCONTO,
  ITENS_PROMOCAO.ITP_PRO_ID,
  ITENS_PROMOCAO.ITP_PRM_ID,
  ITENS_PROMOCAO.ITP_QTD_UPDATE,
  ITENS_PROMOCAO.ITP_DATA_CONTROLE
FROM PABLO.ITENS_PROMOCAO
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE OPERA_PDV
-- findAll OPERA_PDV
SELECT OPERA_PDV.OPE_DATA_ENTRADA,
  OPERA_PDV.OPE_DATA_SAIDA,
  OPERA_PDV.OPE_FNC_ID,
  OPERA_PDV.OPE_PDV_ID,
  OPERA_PDV.OPE_QTD_UPDATE,
  OPERA_PDV.OPE_DATA_CONTROLE
FROM PABLO.OPERA_PDV;
-- findById OPERA_PDV
SELECT OPERA_PDV.OPE_DATA_ENTRADA,
  OPERA_PDV.OPE_DATA_SAIDA,
  OPERA_PDV.OPE_FNC_ID,
  OPERA_PDV.OPE_PDV_ID,
  OPERA_PDV.OPE_QTD_UPDATE,
  OPERA_PDV.OPE_DATA_CONTROLE
FROM PABLO.OPERA_PDV
WHERE OPERA_PDV.OPE_FNC_ID =
  &FNC_ID
AND OPERA_PDV.OPE_PDV_ID =
  &PDV_ID;
-- findByDate OPERA_PDV
SELECT TO_DATE(OPERA_PDV.OPE_DATA_ENTRADA, 'DD/MM/YYYY  HH24:MI'),
  TO_DATE(OPERA_PDV.OPE_DATA_SAIDA, 'DD/MM/YYYY  HH24:MI'),
  OPERA_PDV.OPE_FNC_ID,
  OPERA_PDV.OPE_PDV_ID,
  OPERA_PDV.OPE_QTD_UPDATE,
  OPERA_PDV.OPE_DATA_CONTROLE
FROM PABLO.OPERA_PDV
WHERE OPERA_PDV.OPE_DATA_ENTRADA LIKE
  '&DATA_ENTRADA';
--AND OPERA_PDV.OPE_PDV_ID =
  --&PDV_ID;
-- findByCampo OPERA_PDV
SELECT OPERA_PDV.OPE_DATA_ENTRADA,
  OPERA_PDV.OPE_DATA_SAIDA,
  OPERA_PDV.OPE_FNC_ID,
  OPERA_PDV.OPE_PDV_ID,
  OPERA_PDV.OPE_QTD_UPDATE,
  OPERA_PDV.OPE_DATA_CONTROLE
FROM PABLO.OPERA_PDV
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE PAGAMENTO
-- findAll PAGAMENTO
SELECT PAGAMENTO.PAG_CMP_ID,
  PAGAMENTO.PAG_TIP_ID,
  PAGAMENTO.PAG_VALOR,
  PAGAMENTO.PAG_QTD_UPDATE,
  PAGAMENTO.PAG_DATA_CONTROLE
FROM PABLO.PAGAMENTO;
-- findById PAGAMENTO
SELECT PAGAMENTO.PAG_CMP_ID,
  PAGAMENTO.PAG_TIP_ID,
  PAGAMENTO.PAG_VALOR,
  PAGAMENTO.PAG_QTD_UPDATE,
  PAGAMENTO.PAG_DATA_CONTROLE
FROM PABLO.PAGAMENTO
WHERE PAGAMENTO.PAG_CMP_ID =
  &CMP_ID
AND PAGAMENTO.PAG_TIP_ID =
  &TIP_ID;
-- findByCampo PAGAMENTO
SELECT PAGAMENTO.PAG_CMP_ID,
  PAGAMENTO.PAG_TIP_ID,
  PAGAMENTO.PAG_VALOR,
  PAGAMENTO.PAG_QTD_UPDATE,
  PAGAMENTO.PAG_DATA_CONTROLE
FROM PABLO.PAGAMENTO
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE PDV
-- findAll PDV
SELECT PDV.PDV_ID,
  PDV.PDV_NUMERO,
  PDV.PDV_QTD_UPDATE,
  PDV.PDV_DATA_CONTROLE
FROM PABLO.PDV;
-- findById PDV
SELECT PDV.PDV_ID,
  PDV.PDV_NUMERO,
  PDV.PDV_QTD_UPDATE,
  PDV.PDV_DATA_CONTROLE
FROM PABLO.PDV
WHERE PDV.PDV_ID =
  &PDV_ID;
-- findByNumero PDV
SELECT PDV.PDV_ID,
  PDV.PDV_NUMERO,
  PDV.PDV_QTD_UPDATE,
  PDV.PDV_DATA_CONTROLE
FROM PABLO.PDV
WHERE PDV.PDV_NUMERO =
  '&PDV_NUMERO';
-- findByCampo PDV
SELECT PDV.PDV_ID,
  PDV.PDV_NUMERO,
  PDV.PDV_QTD_UPDATE,
  PDV.PDV_DATA_CONTROLE
FROM PABLO.PDV
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE PRODUTO
-- findAll PRODUTO
SELECT PRODUTO.PRO_ID,
  PRODUTO.PRO_DESCRICAO,
  PRODUTO.PRO_PRECO,
  PRODUTO.PRO_QUANTIDADE,
  PRODUTO.PRO_DATA_VENCIMENTO,
  PRODUTO.PRO_FOR_ID,
  PRODUTO.PRO_CAT_ID,
  PRODUTO.PRO_QTD_UPDATE,
  PRODUTO.PRO_DATA_CONTROLE
FROM PABLO.PRODUTO;
-- findById PRODUTO
SELECT PRODUTO.PRO_ID,
  PRODUTO.PRO_DESCRICAO,
  PRODUTO.PRO_PRECO,
  PRODUTO.PRO_QUANTIDADE,
  PRODUTO.PRO_DATA_VENCIMENTO,
  PRODUTO.PRO_FOR_ID,
  PRODUTO.PRO_CAT_ID,
  PRODUTO.PRO_QTD_UPDATE,
  PRODUTO.PRO_DATA_CONTROLE
FROM PABLO.PRODUTO
WHERE PRODUTO.PRO_ID =
  &PRO_ID;
-- findByDescricao PRODUTO
SELECT PRODUTO.PRO_ID,
  PRODUTO.PRO_DESCRICAO,
  PRODUTO.PRO_PRECO,
  PRODUTO.PRO_QUANTIDADE,
  PRODUTO.PRO_DATA_VENCIMENTO,
  PRODUTO.PRO_FOR_ID,
  PRODUTO.PRO_CAT_ID,
  PRODUTO.PRO_QTD_UPDATE,
  PRODUTO.PRO_DATA_CONTROLE
FROM PABLO.PRODUTO
WHERE PRODUTO.PRO_DESCRICAO LIKE '%&DESCRICAO%';
-- findByCampo PRODUTO
SELECT PRODUTO.PRO_ID,
  PRODUTO.PRO_DESCRICAO,
  PRODUTO.PRO_PRECO,
  PRODUTO.PRO_QUANTIDADE,
  PRODUTO.PRO_DATA_VENCIMENTO,
  PRODUTO.PRO_FOR_ID,
  PRODUTO.PRO_CAT_ID,
  PRODUTO.PRO_QTD_UPDATE,
  PRODUTO.PRO_DATA_CONTROLE
FROM PABLO.PRODUTO
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE PROMOCAO
-- findAll PROMOCAO
SELECT PROMOCAO.PRM_ID,
  PROMOCAO.PRM_DATA_INICIO,
  PROMOCAO.PRM_DATA_FIM,
  PROMOCAO.PRM_NOME,
  PROMOCAO.PRM_QTD_UPDATE,
  PROMOCAO.PRM_DATA_CONTROLE
FROM PABLO.PROMOCAO;
-- findById PROMOCAO
SELECT PROMOCAO.PRM_ID,
  PROMOCAO.PRM_DATA_INICIO,
  PROMOCAO.PRM_DATA_FIM,
  PROMOCAO.PRM_NOME,
  PROMOCAO.PRM_QTD_UPDATE,
  PROMOCAO.PRM_DATA_CONTROLE
FROM PABLO.PROMOCAO
WHERE PROMOCAO.PRM_ID =
  &PRM_ID;
-- findByNome PROMOCAO
SELECT PROMOCAO.PRM_ID,
  PROMOCAO.PRM_DATA_INICIO,
  PROMOCAO.PRM_DATA_FIM,
  PROMOCAO.PRM_NOME,
  PROMOCAO.PRM_QTD_UPDATE,
  PROMOCAO.PRM_DATA_CONTROLE
FROM PABLO.PROMOCAO
WHERE PROMOCAO.PRM_NOME LIKE '%&PRM_NOME%';
-- findByDate PROMOCAO
SELECT PROMOCAO.PRM_ID,
  PROMOCAO.PRM_DATA_INICIO,
  PROMOCAO.PRM_DATA_FIM,
  PROMOCAO.PRM_NOME,
  PROMOCAO.PRM_QTD_UPDATE,
  PROMOCAO.PRM_DATA_CONTROLE
FROM PABLO.PROMOCAO
WHERE PROMOCAO.PRM_DATA_INICIO LIKE '&PRM_DATA';
-- findByCampo PROMOCAO
SELECT PROMOCAO.PRM_ID,
  PROMOCAO.PRM_DATA_INICIO,
  PROMOCAO.PRM_DATA_FIM,
  PROMOCAO.PRM_NOME,
  PROMOCAO.PRM_QTD_UPDATE,
  PROMOCAO.PRM_DATA_CONTROLE
FROM PABLO.PROMOCAO
WHERE
  &CAMPO = '&VALOR';
-- CONSULTAS DE TIPO_PAGAMENTO
-- findAll TIPO_PAGAMENTO
SELECT TIPO_PAGAMENTO.TIP_ID,
  TIPO_PAGAMENTO.TIP_DESCRICAO,
  TIPO_PAGAMENTO.TIP_QTD_UPDATE,
  TIPO_PAGAMENTO.TIP_DATA_CONTROLE
FROM PABLO.TIPO_PAGAMENTO;
-- findById TIPO_PAGAMENTO
SELECT TIPO_PAGAMENTO.TIP_ID,
  TIPO_PAGAMENTO.TIP_DESCRICAO,
  TIPO_PAGAMENTO.TIP_QTD_UPDATE,
  TIPO_PAGAMENTO.TIP_DATA_CONTROLE
FROM PABLO.TIPO_PAGAMENTO
WHERE TIPO_PAGAMENTO.TIP_ID =
  &TIP_ID;
-- findByNome TIPO_PAGAMENTO
SELECT TIPO_PAGAMENTO.TIP_ID,
  TIPO_PAGAMENTO.TIP_DESCRICAO,
  TIPO_PAGAMENTO.TIP_QTD_UPDATE,
  TIPO_PAGAMENTO.TIP_DATA_CONTROLE
FROM PABLO.TIPO_PAGAMENTO
WHERE TIPO_PAGAMENTO.TIP_DESCRICAO LIKE '%&TIP_DESCRICAO%';
-- findByCampo TIPO_PAGAMENTO
SELECT TIPO_PAGAMENTO.TIP_ID,
  TIPO_PAGAMENTO.TIP_DESCRICAO,
  TIPO_PAGAMENTO.TIP_QTD_UPDATE,
  TIPO_PAGAMENTO.TIP_DATA_CONTROLE
FROM PABLO.TIPO_PAGAMENTO
WHERE
  &CAMPO = '&VALOR';